language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.0
env:
  global:
    - GITHUB_CLIENT_ID=123abc432fdsfde
    - GITHUB_CLIENT_SECRET=nu584h7g584hnf9ewpmvfen
    - APP_HOSTNAME=editor.example.com
deploy:
  provider: heroku
  api_key:
    secure: D8r/NjVLT4VQiTmk+EH2VBAtzvffmI54Nwa5GinejZ45z9h4ZksshQW+LMw4IQkHprPaFpLPOGNO3U7X9VEAw9K5G5yCoBexC9C5EMpQMi2qpbaHHvTGzVE1Nc/pLLx1aEzz8IsVshMU63SC/Q3OK6QUtrauLNSQh/i+IvwuCHo=
  app: githubeditor
  on:
    repo: theodi/github_editor
